name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
        pip install black isort  # ensure formatting tools are available

    - name: Lint with flake8
      run: |
        flake8 game_of_life tests

    - name: Type-check with mypy
      run: |
        mypy --config-file mypy.ini game_of_life

    - name: Check code formatting with black
      run: |
        black --check .

    - name: Check import sorting with isort
      run: |
        isort --check-only .

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q
